apiVersion: v1
kind: Service
metadata:
  name: dotnet-service
  namespace: default
spec:
  selector:
    app: dotnet-web
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30000
